name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:prod

    - name: Add .htaccess
      run: |
        echo "RewriteEngine On" >> dist/bangis/.htaccess
        echo "# If an existing asset or directory is requested go to it as it is" >> dist/bangis/.htaccess
        echo "RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]" >> dist/bangis/.htaccess
        echo "RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d" >> dist/bangis/.htaccess
        echo "RewriteRule ^ - [L]" >> dist/bangis/.htaccess
        echo "" >> dist/bangis/.htaccess
        echo "# If the requested resource doesn't exist, use index.html" >> dist/bangis/.htaccess
        echo "RewriteRule ^ /index.html" >> dist/bangis/.htaccess

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/bangis # Change this to your build directory
        enable_jekyll: true
        publish_branch: prod
